### ISSUE TITLE
App Names

### ISSUE THREAD

**Issue by RobertoAF** [CS-DictionaryTeam/switch#16]
Hey,
Since we need to start work on our splash screen as soon as possible, it's time to vote for our app name.
Please take a look at the App Names.gdoc in our project folder and choose your top 3 choices by Saturday morning. Let me know if you need extra time.
Thanks.

**Comment by potatoyenn** [comment]
@RobertoAF current status of this?

**Comment by RobertoAF** [comment]
We're still waiting for one vote.

**Comment by arangob** [comment]
sorry! my vote is in.

**Comment by potatoyenn** [comment]
Final Vote: Switch!

**Comment by RobertoAF** [comment]
Yay!
