### ISSUE TITLE
Add memes 

### ISSUE THREAD

**Issue by yparks** [CS-DictionaryTeam/switch#17]
Hi guys, I just placed a folder with few memes pics, please feel free to add more memes if you like to add on our main page. Thanks.
![add memes](https://cloud.githubusercontent.com/assets/25780064/25288805/db1cad02-267b-11e7-920f-949ca60d3ac2.jpeg)

**Comment by RobertoAF** [comment]
@yparks How many should each person collect? Are five okay (for a total of twenty)?

**Comment by RobertoAF** [comment]
@yparks I forgot to ask about the subject/theme. Should they be only related to Java or can they be about Computer Science in general as well?
So, for example, would this be okay?
![image](https://cloud.githubusercontent.com/assets/13029161/25291356/96b32316-2686-11e7-8ac5-d620f2c35572.png)

**Comment by RobertoAF** [comment]
@yparks 
Are these okay?

![adalovelace](https://cloud.githubusercontent.com/assets/13029161/25310058/6c82fa16-2790-11e7-94ab-16ca7a2885be.jpg)
![nojava](https://cloud.githubusercontent.com/assets/13029161/25308789/72165a1e-2771-11e7-818c-f8f29c66f29e.jpg)
![roses](https://cloud.githubusercontent.com/assets/13029161/25308790/72198c02-2771-11e7-9c24-6ea42f876197.jpg)
![stack](https://cloud.githubusercontent.com/assets/13029161/25308791/721bd020-2771-11e7-81bf-2aecfe0e3bc3.png)
![twostates](https://cloud.githubusercontent.com/assets/13029161/25308792/721dffda-2771-11e7-8b16-b640fe3e9263.jpg)

**Comment by potatoyenn** [comment]
@RobertoAF @yparks the baby logic photo was difficult to read on my laptop. We should stick to memes with a larger font size?

5 sounds like a good number. I'll upload mine tonight.

**Comment by RobertoAF** [comment]
@potatoyenn 
Good thinking. I updated it. Thanks!
