### ISSUE TITLE
Merge Code for Memes

### ISSUE THREAD

**Issue by potatoyenn** [CS-DictionaryTeam/switch#44]
Goal: to make image carousel switch through memes automatically.

**Comment by RobertoAF** [comment]
Update:
<img width="412" alt="screen shot 2017-05-04 at 2 07 08 am" src="https://cloud.githubusercontent.com/assets/13029161/25697102/8512496a-306e-11e7-8127-a2f5ca48d145.png">

**Comment by RobertoAF** [comment]
@potatoyenn @yparks 
I'm wondering...how many memes should there be in total and are do they all display?
