### ISSUE TITLE
Word of the Day

### ISSUE THREAD

**Issue by potatoyenn** [CS-DictionaryTeam/switch#45]
Make Word of the Day visually more appealing and readable.

**Comment by RobertoAF** [comment]
Here's Ying's and Ashley's updated Home/Main :
<img width="484" alt="screen shot 2017-05-04 at 1 14 09 am" src="https://cloud.githubusercontent.com/assets/13029161/25696114/c8f0c962-306a-11e7-9371-e509d9241602.png">

**Comment by RobertoAF** [comment]
Update Th.May.4.2017:

<img width="379" alt="screen shot 2017-05-04 at 1 26 26 pm" src="https://cloud.githubusercontent.com/assets/13029161/25723701/fa6c95f8-30cd-11e7-9f87-8406ccdee7e8.png">

**Comment by RobertoAF** [comment]
Update Th.May.4.2017:
<img width="382" alt="screen shot 2017-05-04 at 2 20 24 pm" src="https://cloud.githubusercontent.com/assets/13029161/25725580/75f67aa2-30d5-11e7-8354-bab4e3b974bf.png">
