### ISSUE TITLE
HistoryListFragment

### ISSUE THREAD

**Issue by potatoyenn** [CS-DictionaryTeam/switch#46]
White space issue

**Comment by RobertoAF** [comment]
Any suggestions on how to fix this white space issue?

<img width="437" alt="screen shot 2017-04-29 at 9 00 41 pm" src="https://cloud.githubusercontent.com/assets/13029161/25561351/fe6564a8-2d1e-11e7-9cf8-db5b8edd4ce7.png">

Here's the original history.xml code.
<img width="589" alt="screen shot 2017-04-29 at 9 02 16 pm" src="https://cloud.githubusercontent.com/assets/13029161/25561356/32fa63da-2d1f-11e7-87b7-4d23e6f97a21.png">

**Comment by arangob** [comment]
i think it might be the fragment

**Comment by RobertoAF** [comment]
So I adjusted the the layout height from
<img width="305" alt="screen shot 2017-04-30 at 8 29 53 pm" src="https://cloud.githubusercontent.com/assets/13029161/25571388/10695b6c-2de4-11e7-8a93-8058a7819218.png">
to
<img width="319" alt="screen shot 2017-04-30 at 8 35 14 pm" src="https://cloud.githubusercontent.com/assets/13029161/25571447/9669076c-2de4-11e7-8a1c-c9cdfe012cea.png">

So, it fixed the height issue:
<img width="377" alt="screen shot 2017-04-30 at 8 36 04 pm" src="https://cloud.githubusercontent.com/assets/13029161/25571459/b73fb76a-2de4-11e7-905a-18ed4288a8da.png">

**Comment by RobertoAF** [comment]
I'm wondering how to keep the bottom navigation bar visible?

**Comment by RobertoAF** [comment]
Specifying the layout height could be a short-term fix:
<img width="309" alt="screen shot 2017-04-30 at 9 38 36 pm" src="https://cloud.githubusercontent.com/assets/13029161/25572177/74ac7894-2ded-11e7-9f42-58d955692626.png">
<img width="335" alt="screen shot 2017-04-30 at 9 38 16 pm" src="https://cloud.githubusercontent.com/assets/13029161/25572454/1f54ed10-2df0-11e7-94f7-06ba57bcde1b.png">

**Comment by RobertoAF** [comment]
I finally solved some of the db issues and got the history to only display distinct terms and limit it to 50.
We now have a working History class! Here's the query statement:
<img width="726" alt="screen shot 2017-04-30 at 10 47 47 pm" src="https://cloud.githubusercontent.com/assets/13029161/25573122/1ca40306-2df7-11e7-8e3f-fe282e65e03c.png">

Here is the final result:
<img width="331" alt="screen shot 2017-04-30 at 10 44 30 pm" src="https://cloud.githubusercontent.com/assets/13029161/25573073/a0c29e14-2df6-11e7-8e47-cff32c0c3147.png">

**Comment by RobertoAF** [comment]
+ The background color needs to be changed in history so that there is a uniform color scheme and style.

**Comment by potatoyenn** [comment]
@RobertoAF safe to close now?

**Comment by RobertoAF** [comment]
Not yet, we are working on an enhancement.

**Comment by RobertoAF** [comment]
Update Th.May.4.2017:
<img width="387" alt="screen shot 2017-05-04 at 12 46 16 pm" src="https://cloud.githubusercontent.com/assets/13029161/25722111/c9145370-30c7-11e7-8b04-faa007187030.png">
