### ISSUE TITLE
Splash/Launch Screen

### ISSUE THREAD

**Issue by RobertoAF** [CS-DictionaryTeam/switch#47]
Hey guys, 

Here is the final version of v.1 for our splash screen.
Let me know if you think there are any necessary adjustments we need to make before I add it to our dictionary tomorrow...

<img width="364" alt="screen shot 2017-04-29 at 8 52 39 pm" src="https://cloud.githubusercontent.com/assets/13029161/25561296/f406da60-2d1d-11e7-8e2b-bf7235fc38b6.png">

<img width="652" alt="screen shot 2017-04-29 at 8 52 15 pm" src="https://cloud.githubusercontent.com/assets/13029161/25561295/f22f889a-2d1d-11e7-8068-8cbdbe5df08a.png">

**Comment by RobertoAF** [comment]
Here's design doc for launch screens: 
https://material.io/guidelines/patterns/launch-screens.html#

**Comment by RobertoAF** [comment]
Here's a link to some info on launch screens (based on Google's Material Design guidelines, which is their visual design framework) in case you're interested:
[https://material.io/guidelines/patterns/launch-screens.html#](url)

**Comment by RobertoAF** [comment]
I just added the splash screen; however, I am encountering the problem of it loading too quickly? In a vertical position, it lasts a fraction of a second, and in landscape mode, it probably lasts milliseconds. Since I don't even see it, that's just a guess. Should we put a timer on it? Would three seconds suffice ?

**Comment by RobertoAF** [comment]
I changed it to 2s. Check it out.
[Splash.zip](https://github.com/CS-DictionaryTeam/switch/files/967146/Splash.zip)

**Comment by RobertoAF** [comment]
@yparks @potatoyenn @arangob 
Ok, so we're working on an icon with an s inscribed in a square as our logo using the same background and font color as the splash screen.

Do you think we should try to add this logo to the splash screen or to keep it as it is?

**Comment by arangob** [comment]
my vote is keep as is.

**Comment by RobertoAF** [comment]
K. I'll update you when the icon is finished so that we can add it to our project.
